repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: flake8
      args:
        - --config=setup.cfg
        - --ignore=S403,S605,S607,S301
      additional_dependencies:
        - flake8-bandit
        - flake8-eradicate
        - flake8-isort
        - flake8-return
        - pep8-naming
